// ─────────────────────────────────────────────────────────────────────────────
// Config / Strings  —  all UI strings in bn + en
//
// Usage:
//   window.t('key')              → translated string for current lang
//   window.t('key', {x: val})   → with variable substitution  ({x} → val)
//   window.AHLang                → current lang ('bn' | 'en'), set by App.jsx
// ─────────────────────────────────────────────────────────────────────────────

window.AHStrings = {
  bn: {
    // ── Navigation ────────────────────────────────────────────────────────
    nav_dashboard:  'ড্যাশবোর্ড',
    nav_history:    'লেনদেন',
    nav_debts:      'দেনা-পাওনা',
    nav_budget:     'বাজেট',
    nav_reports:    'প্রতিবেদন',
    nav_reminders:  'রিমাইন্ডার',
    nav_settings:   'সেটিংস',

    // ── Screen titles ─────────────────────────────────────────────────────
    screen_dashboard_eyebrow: 'হোম',
    screen_dashboard_sub:     'এই মাসের আর্থিক চিত্র দেখুন',
    screen_history_eyebrow:   'লেনদেন',
    screen_history_title:     'সকল হিসাব',
    screen_history_sub:       'খরচের ইতিহাস ও ফিল্টার',
    screen_debts_eyebrow:     'দেনা-পাওনা',
    screen_debts_title:       'ধার-পরিচালনা',
    screen_debts_sub:         'ব্যক্তিগত দেনা ও পাওনা',
    screen_budget_eyebrow:    'বাজেট',
    screen_budget_title:      'মাসিক পরিকল্পনা',
    screen_budget_sub:        'বাজেট ও খরচের তুলনা',
    screen_reports_eyebrow:   'প্রতিবেদন',
    screen_reports_title:     'বিস্তারিত প্রতিবেদন',
    screen_reports_sub:       'শ্রেণী ও সময় অনুযায়ী বিশ্লেষণ',
    screen_reminders_eyebrow: 'রিমাইন্ডার',
    screen_reminders_title:   'সক্রিয় রিমাইন্ডার',
    screen_reminders_sub:     'গুরুত্বপূর্ণ স্মরণ ও সতর্কতা',
    screen_settings_eyebrow:  'সেটিংস',
    screen_settings_title:    'অ্যাপ সেটিংস',
    screen_settings_sub:      'প্রোফাইল ও পছন্দসমূহ',

    // ── Top bar ───────────────────────────────────────────────────────────
    topbar_menu:    'মেনু',
    topbar_search:  'খুঁজুন',
    topbar_notif:   'নোটিফিকেশন',
    welcome_prefix: 'স্বাগতম, ',

    // ── Sidebar / nav ─────────────────────────────────────────────────────
    n_brand:     'আমার হিসাব',
    n_brand_sub: 'ব্যক্তিগত অর্থ',
    n_close:     'বন্ধ করুন',
    n_add_tx:    'হিসাব যোগ করুন',
    n_main_menu: 'মূল মেনু',
    n_others:    'অন্যান্য',

    // ── Settings ──────────────────────────────────────────────────────────
    set_theme_title:      'থিম রঙ',
    set_theme_sub:        'আপনার পছন্দের প্যালেট বাছুন',
    set_lang_title:       'ভাষা',
    set_lang_sub:         'অ্যাপের ভাষা পরিবর্তন করুন',
    set_lang_bn:          'বাংলা',
    set_lang_en:          'English',
    set_notif_title:      'নোটিফিকেশন',
    set_notif_sub:        'কখন আমরা আপনাকে জানাব',
    set_budget_alert:     'বাজেট সতর্কতা',
    set_budget_alert_sub: 'বাজেটের ৮০% খরচ হলে জানাব',
    set_debt_remind:      'দেনা-পাওনা স্মরণ',
    set_debt_remind_sub:  'সাত দিনের বেশি পুরোনো ধার মনে করিয়ে দেব',
    set_data_title:       'ডেটা ব্যবস্থাপনা',
    set_data_sub:         'আপনার সংরক্ষিত তথ্য পরিচালনা',
    set_data_reset:       'ডেটা রিসেট',
    set_data_delete:      'সব ডেটা মুছুন',
    dlg_reset_title:      'ডেটা রিসেট',
    dlg_reset_msg:        'সব হিসাব, দেনা-পাওনা ও বাজেট মুছে গিয়ে শূন্য থেকে শুরু হবে। এই কাজ ফেরানো যাবে না।',
    dlg_reset_ok:         'রিসেট করুন',
    dlg_delete_title:     'সব ডেটা মুছুন',
    dlg_delete_msg:       'আপনার সব ব্যক্তিগত ডেটা মুছে যাবে। নিশ্চিত?',
    dlg_delete_ok:        'মুছে ফেলুন',
    toast_reset:          'ডেটা রিসেট হয়েছে',
    toast_deleted:        'সব ডেটা মুছে ফেলা হয়েছে',

    // ── Dashboard ─────────────────────────────────────────────────────────
    d_balance_eyebrow:   'বর্তমান ব্যালেন্স',
    d_budget_remaining:  'মাসিক বাজেট থেকে ৳{amt} বাকি আছে',
    d_budget_exceeded:   'বাজেট অতিক্রম হয়েছে ৳{amt}',
    d_edit_budget:       'বাজেট সম্পাদনা',
    d_spent_label:       '৳{amt} খরচ হয়েছে',
    d_budget_label:      '৳{amt} বাজেট',
    d_today_spend:       'আজকের খরচ',
    d_daily_avg:         'দৈনিক গড়',
    d_budget_use:        'বাজেট ব্যবহার',
    d_total_spend:       'মোট খরচ',
    d_of_budget:         'বাজেটের',
    d_monthly_budget:    'মাসিক বাজেট',
    d_borrowed:          'আমি ধার নিয়েছি',
    d_borrowed_from:     '{n} জন ব্যক্তির কাছে',
    d_lent:              'আমি ধার দিয়েছি',
    d_lent_to:           '{n} জন ব্যক্তিকে',
    d_weekly_chart:      'সাপ্তাহিক খরচ',
    d_weekly_chart_sub:  'গত ৭ দিনের খরচের চিত্র',
    d_details:           'বিস্তারিত',
    d_cat_breakdown:     'খরচের ধরন',
    d_cat_breakdown_sub: 'এই মাসে শ্রেণী অনুযায়ী',
    d_no_spend:          'এখনো কোন খরচ নেই',
    d_add_first:         'আপনার প্রথম খরচ যোগ করুন',
    d_total:             'মোট',
    d_recent_tx:         'সাম্প্রতিক হিসাব',
    d_recent_tx_sub:     'সর্বশেষ লেনদেনসমূহ',
    d_see_all:           'সব দেখুন',
    d_debts_title:       'দেনা-পাওনা',
    d_debts_sub:         'সাম্প্রতিক ধার-পরিচালনা',

    // ── History ───────────────────────────────────────────────────────────
    h_weekly:     'সাপ্তাহিক',
    h_monthly:    'মাসিক',
    h_all:        'সব',
    h_total_spend:'মোট খরচ',
    h_tx_count:   '{n}টি লেনদেন',
    h_daily_avg:  'দৈনিক গড়',
    h_days:       '{n} দিনে',
    h_max:        'সর্বোচ্চ',
    h_max_day:    'একদিনের সর্বোচ্চ',
    h_all_tx:     'সকল লেনদেন',
    h_filter_hint:'তারিখ ও ধরন অনুযায়ী ফিল্টার করুন',
    h_search_ph:  'খুঁজুন...',
    h_all_types:  'সব ধরন',
    h_no_tx:      'কোন লেনদেন পাওয়া যায়নি',
    h_no_tx_sub:  'ফিল্টার পরিবর্তন করুন বা নতুন হিসাব যোগ করুন',

    // ── Debts ─────────────────────────────────────────────────────────────
    db_borrowed:      'আমি ধার নিয়েছি',
    db_borrowed_sub:  '{n} জন ব্যক্তির কাছে দিতে হবে',
    db_lent:          'আমি ধার দিয়েছি',
    db_lent_sub:      '{n} জন ব্যক্তির কাছ থেকে পাব',
    db_net:           'নেট পাওনা',
    db_net_positive:  'মোট পাওনা বেশি',
    db_net_negative:  'মোট দেনা বেশি',
    db_list_title:    'দেনা-পাওনার তালিকা',
    db_list_sub:      'আপনার সকল ব্যক্তিগত লেনদেন',
    db_add_new:       'নতুন যোগ করুন',
    db_all:           'সব',
    db_borrowed_tab:  'ধার নেওয়া',
    db_lent_tab:      'ধার দেওয়া',
    db_empty:         'কোন দেনা-পাওনা নেই',
    db_empty_sub:     'নতুন ধার-পরিচালনা যোগ করুন',

    // ── Budget ────────────────────────────────────────────────────────────
    b_title:     'এই মাসের বাজেট',
    b_edit:      'বাজেট সম্পাদনা',
    b_total:     'মোট বাজেট',
    b_spent:     'খরচ হয়েছে',
    b_remaining: 'বাকি আছে',
    b_used_pct:  '{pct}% ব্যবহৃত',
    b_days_left: '{n} দিন বাকি',
    b_warn_title:'সতর্কতা: বাজেটের কাছাকাছি',
    b_warn_msg:  'আপনি ইতিমধ্যে {pct}% খরচ করেছেন',
    b_over_title:'বাজেট অতিক্রান্ত!',
    b_over_msg:  'সীমার চেয়ে ৳{amt} বেশি খরচ হয়েছে',
    b_cat_title: 'শ্রেণী অনুযায়ী খরচ',
    b_cat_sub:   'প্রতিটি ধরনের খরচের বিশ্লেষণ',

    // ── Reports ───────────────────────────────────────────────────────────
    r_weekly:      'সাপ্তাহিক',
    r_monthly:     'মাসিক',
    r_yearly:      'বার্ষিক',
    r_all:         'সব',
    r_total_spend: 'মোট খরচ',
    r_tx_count:    '{n}টি লেনদেন',
    r_daily_avg:   'দৈনিক গড়',
    r_per_day:     'প্রতি দিন',
    r_max:         'সর্বোচ্চ',
    r_single_tx:   'একটি লেনদেন',
    r_cat_title:   'শ্রেণী অনুযায়ী খরচ',
    r_cat_sub:     'বিস্তারিত বিশ্লেষণ',
    r_csv:         'CSV ডাউনলোড',
    r_empty:       'কোন লেনদেন পাওয়া যায়নি',
    r_empty_sub:   'অন্য সময়সীমা বাছাই করুন',
    r_csv_date:    'তারিখ',
    r_csv_desc:    'বিবরণ',
    r_csv_cat:     'শ্রেণী',
    r_csv_amt:     'পরিমাণ',
    r_csv_done:    'CSV ডাউনলোড হয়েছে',

    // ── Reminders ─────────────────────────────────────────────────────────
    rm_borrowed_remind: '{name}-কে ৳{amt} ফেরত দেওয়া বাকি',
    rm_lent_remind:     '{name}-এর কাছ থেকে ৳{amt} পাবেন',
    rm_days_ago:        '{n} দিন আগে',
    rm_borrowed_type:   'ধার নেওয়া',
    rm_lent_type:       'ধার দেওয়া',
    rm_budget_near:     'বাজেট সীমার কাছাকাছি',
    rm_budget_near_sub: '{pct}% খরচ হয়েছে · {days} দিন বাকি',
    rm_budget_over:     'বাজেট অতিক্রান্ত!',
    rm_budget_over_sub: 'সীমার চেয়ে ৳{amt} বেশি',
    rm_title:           'সক্রিয় রিমাইন্ডার',
    rm_sub:             'গুরুত্বপূর্ণ স্মরণ ও সতর্কতা',
    rm_empty:           'কোন রিমাইন্ডার নেই',
    rm_empty_sub:       'আপনার সবকিছু ঠিক আছে',

    // ── Add Transaction modal ─────────────────────────────────────────────
    mtx_title_add:       'হিসাব যোগ করুন',
    mtx_title_edit:      'হিসাব সম্পাদনা',
    mtx_close:           'বন্ধ করুন',
    mtx_expense:         'খরচ',
    mtx_income:          'আয়',
    mtx_amount_label:    'টাকার পরিমাণ',
    mtx_cat_label:       'খরচের ধরন',
    mtx_desc_label:      'বিবরণ',
    mtx_desc_ph:         'যেমন: দুপুরের খাবার',
    mtx_date_label:      'তারিখ',
    mtx_cancel:          'বাতিল',
    mtx_saving:          '...সংরক্ষণ',
    mtx_save:            'সংরক্ষণ করুন',
    mtx_err_amount:      'পরিমাণ লিখুন',
    mtx_err_invalid:     'বৈধ পরিমাণ লিখুন',
    mtx_err_large:       'পরিমাণ অনেক বেশি',
    mtx_err_date:        'তারিখ লিখুন',
    mtx_err_future:      'ভবিষ্যৎ তারিখ গ্রহণযোগ্য নয়',

    // ── Add Debt modal ────────────────────────────────────────────────────
    mdb_title_add:    'দেনা-পাওনা যোগ করুন',
    mdb_title_edit:   'দেনা-পাওনা সম্পাদনা',
    mdb_close:        'বন্ধ করুন',
    mdb_borrowed:     'আমি ধার নিয়েছি',
    mdb_lent:         'আমি ধার দিয়েছি',
    mdb_name_label:   'ব্যক্তির নাম',
    mdb_name_ph:      'যেমন: রহিম ভাই',
    mdb_amount_label: 'টাকার পরিমাণ',
    mdb_date_label:   'তারিখ',
    mdb_note_label:   'নোট (ঐচ্ছিক)',
    mdb_note_ph:      'যেমন: মাস শেষে ফেরত',
    mdb_cancel:       'বাতিল',
    mdb_saving:       '...সংরক্ষণ',
    mdb_save:         'সংরক্ষণ করুন',
    mdb_err_name:     'নাম লিখুন',
    mdb_err_name_long:'নাম ছোট রাখুন',
    mdb_err_amount:   'পরিমাণ লিখুন',
    mdb_err_invalid:  'বৈধ পরিমাণ লিখুন',
    mdb_err_large:    'পরিমাণ অনেক বেশি',
    mdb_err_date:     'তারিখ লিখুন',

    // ── Budget modal ──────────────────────────────────────────────────────
    mb_title:        'মাসিক বাজেট নির্ধারণ',
    mb_close:        'বন্ধ করুন',
    mb_desc:         'এই মাসে আপনি সর্বোচ্চ কত টাকা খরচ করতে চান? আমরা আপনাকে সীমার কাছাকাছি পৌঁছালে জানাব।',
    mb_amount_label: 'বাজেট পরিমাণ',
    mb_cancel:       'বাতিল',
    mb_confirm:      'নিশ্চিত করুন',
    mb_err_invalid:  'বৈধ পরিমাণ লিখুন',
    mb_err_large:    'পরিমাণ অনেক বেশি',

    // ── Widgets ───────────────────────────────────────────────────────────
    w_edit:   'সম্পাদনা',
    w_delete: 'মুছুন',
    w_settle: 'মিটানো',

    // ── App-level toasts & dialogs ────────────────────────────────────────
    app_tx_updated:      'হিসাব আপডেট হয়েছে',
    app_tx_saved:        'হিসাব সংরক্ষণ হয়েছে',
    app_debt_updated:    'দেনা-পাওনা আপডেট হয়েছে',
    app_debt_saved:      'দেনা-পাওনা সংরক্ষণ হয়েছে',
    app_debt_settled:    'মিটানো হিসেবে চিহ্নিত হয়েছে',
    app_tx_deleted:      'লেনদেন মুছে ফেলা হয়েছে',
    app_budget_saved:    'বাজেট সংরক্ষণ হয়েছে',
    dlg_delete_tx_title: 'লেনদেন মুছুন',
    dlg_delete_tx_msg:   '"{desc}" — ৳{amt} মুছে ফেলবেন?',
    dlg_delete_tx_ok:    'মুছুন',
    dlg_settle_title:    'মিটানো নিশ্চিত করুন',
    dlg_settle_msg:      '{name} — ৳{amt} মিটানো হিসেবে গণ্য হবে।',
    dlg_settle_ok:       'মিটানো',
    dlg_signout_title:   'সাইন আউট',
    dlg_signout_msg:     'আপনি কি সাইন আউট করতে চান? আপনার ডেটা এই ডিভাইসে অতিথি মোডে থাকবে।',
    dlg_signout_ok:      'সাইন আউট',
    toast_signout:       'সাইন আউট হয়েছে',
    toast_signout_err:   'সাইন আউটে সমস্যা হয়েছে',
  },

  en: {
    // ── Navigation ────────────────────────────────────────────────────────
    nav_dashboard:  'Dashboard',
    nav_history:    'Transactions',
    nav_debts:      'Debts',
    nav_budget:     'Budget',
    nav_reports:    'Reports',
    nav_reminders:  'Reminders',
    nav_settings:   'Settings',

    // ── Screen titles ─────────────────────────────────────────────────────
    screen_dashboard_eyebrow: 'Home',
    screen_dashboard_sub:     'View this month\'s financial overview',
    screen_history_eyebrow:   'Transactions',
    screen_history_title:     'All Records',
    screen_history_sub:       'Transaction history & filters',
    screen_debts_eyebrow:     'Debts',
    screen_debts_title:       'Debt Management',
    screen_debts_sub:         'Personal debts & credits',
    screen_budget_eyebrow:    'Budget',
    screen_budget_title:      'Monthly Plan',
    screen_budget_sub:        'Budget vs spending comparison',
    screen_reports_eyebrow:   'Reports',
    screen_reports_title:     'Detailed Reports',
    screen_reports_sub:       'Analysis by category & time',
    screen_reminders_eyebrow: 'Reminders',
    screen_reminders_title:   'Active Reminders',
    screen_reminders_sub:     'Important reminders & alerts',
    screen_settings_eyebrow:  'Settings',
    screen_settings_title:    'App Settings',
    screen_settings_sub:      'Profile & preferences',

    // ── Top bar ───────────────────────────────────────────────────────────
    topbar_menu:    'Menu',
    topbar_search:  'Search',
    topbar_notif:   'Notifications',
    welcome_prefix: 'Welcome, ',

    // ── Sidebar / nav ─────────────────────────────────────────────────────
    n_brand:     'Amar Hisab',
    n_brand_sub: 'Personal Finance',
    n_close:     'Close',
    n_add_tx:    'Add Transaction',
    n_main_menu: 'Main Menu',
    n_others:    'More',

    // ── Settings ──────────────────────────────────────────────────────────
    set_theme_title:      'Theme Color',
    set_theme_sub:        'Choose your preferred palette',
    set_lang_title:       'Language',
    set_lang_sub:         'Change the app language',
    set_lang_bn:          'বাংলা',
    set_lang_en:          'English',
    set_notif_title:      'Notifications',
    set_notif_sub:        'When we will notify you',
    set_budget_alert:     'Budget Alert',
    set_budget_alert_sub: 'Alert when 80% of budget is spent',
    set_debt_remind:      'Debt Reminder',
    set_debt_remind_sub:  'Remind for debts older than 7 days',
    set_data_title:       'Data Management',
    set_data_sub:         'Manage your stored information',
    set_data_reset:       'Reset Data',
    set_data_delete:      'Delete All Data',
    dlg_reset_title:      'Reset Data',
    dlg_reset_msg:        'All transactions, debts, and budget will be cleared. This cannot be undone.',
    dlg_reset_ok:         'Reset',
    dlg_delete_title:     'Delete All Data',
    dlg_delete_msg:       'All your personal data will be deleted. Are you sure?',
    dlg_delete_ok:        'Delete',
    toast_reset:          'Data has been reset',
    toast_deleted:        'All data has been deleted',

    // ── Dashboard ─────────────────────────────────────────────────────────
    d_balance_eyebrow:   'Current Balance',
    d_budget_remaining:  '৳{amt} remaining from monthly budget',
    d_budget_exceeded:   'Budget exceeded by ৳{amt}',
    d_edit_budget:       'Edit Budget',
    d_spent_label:       '৳{amt} spent',
    d_budget_label:      '৳{amt} budget',
    d_today_spend:       "Today's Spending",
    d_daily_avg:         'Daily Average',
    d_budget_use:        'Budget Used',
    d_total_spend:       'Total Spending',
    d_of_budget:         'of budget',
    d_monthly_budget:    'Monthly Budget',
    d_borrowed:          'I Borrowed',
    d_borrowed_from:     'from {n} person(s)',
    d_lent:              'I Lent',
    d_lent_to:           'to {n} person(s)',
    d_weekly_chart:      'Weekly Spending',
    d_weekly_chart_sub:  'Last 7 days spending overview',
    d_details:           'Details',
    d_cat_breakdown:     'Spending by Category',
    d_cat_breakdown_sub: 'This month by category',
    d_no_spend:          'No spending yet',
    d_add_first:         'Add your first expense',
    d_total:             'Total',
    d_recent_tx:         'Recent Transactions',
    d_recent_tx_sub:     'Latest transactions',
    d_see_all:           'See All',
    d_debts_title:       'Debts',
    d_debts_sub:         'Recent debt activity',

    // ── History ───────────────────────────────────────────────────────────
    h_weekly:      'Weekly',
    h_monthly:     'Monthly',
    h_all:         'All',
    h_total_spend: 'Total Spending',
    h_tx_count:    '{n} transactions',
    h_daily_avg:   'Daily Average',
    h_days:        'in {n} days',
    h_max:         'Highest',
    h_max_day:     'Highest in a day',
    h_all_tx:      'All Transactions',
    h_filter_hint: 'Filter by date and type',
    h_search_ph:   'Search...',
    h_all_types:   'All Types',
    h_no_tx:       'No transactions found',
    h_no_tx_sub:   'Change filter or add a new record',

    // ── Debts ─────────────────────────────────────────────────────────────
    db_borrowed:     'I Borrowed',
    db_borrowed_sub: 'to pay back to {n} person(s)',
    db_lent:         'I Lent',
    db_lent_sub:     'to receive from {n} person(s)',
    db_net:          'Net Balance',
    db_net_positive: 'Net receivable is higher',
    db_net_negative: 'Net payable is higher',
    db_list_title:   'Debt List',
    db_list_sub:     'All your personal debts',
    db_add_new:      'Add New',
    db_all:          'All',
    db_borrowed_tab: 'Borrowed',
    db_lent_tab:     'Lent',
    db_empty:        'No debts found',
    db_empty_sub:    'Add a new debt entry',

    // ── Budget ────────────────────────────────────────────────────────────
    b_title:     "This Month's Budget",
    b_edit:      'Edit Budget',
    b_total:     'Total Budget',
    b_spent:     'Spent',
    b_remaining: 'Remaining',
    b_used_pct:  '{pct}% used',
    b_days_left: '{n} days remaining',
    b_warn_title:'Warning: Near Budget Limit',
    b_warn_msg:  'You have already spent {pct}%',
    b_over_title:'Budget Exceeded!',
    b_over_msg:  '৳{amt} over budget limit',
    b_cat_title: 'Spending by Category',
    b_cat_sub:   'Analysis of each category',

    // ── Reports ───────────────────────────────────────────────────────────
    r_weekly:      'Weekly',
    r_monthly:     'Monthly',
    r_yearly:      'Yearly',
    r_all:         'All',
    r_total_spend: 'Total Spending',
    r_tx_count:    '{n} transactions',
    r_daily_avg:   'Daily Average',
    r_per_day:     'per day',
    r_max:         'Highest',
    r_single_tx:   'single transaction',
    r_cat_title:   'Spending by Category',
    r_cat_sub:     'Detailed analysis',
    r_csv:         'Download CSV',
    r_empty:       'No transactions found',
    r_empty_sub:   'Try a different time range',
    r_csv_date:    'Date',
    r_csv_desc:    'Description',
    r_csv_cat:     'Category',
    r_csv_amt:     'Amount',
    r_csv_done:    'CSV downloaded',

    // ── Reminders ─────────────────────────────────────────────────────────
    rm_borrowed_remind: 'Need to return ৳{amt} to {name}',
    rm_lent_remind:     'To receive ৳{amt} from {name}',
    rm_days_ago:        '{n} days ago',
    rm_borrowed_type:   'Borrowed',
    rm_lent_type:       'Lent',
    rm_budget_near:     'Near Budget Limit',
    rm_budget_near_sub: '{pct}% spent · {days} days left',
    rm_budget_over:     'Budget Exceeded!',
    rm_budget_over_sub: '৳{amt} over limit',
    rm_title:           'Active Reminders',
    rm_sub:             'Important reminders & alerts',
    rm_empty:           'No reminders',
    rm_empty_sub:       'Everything is in order',

    // ── Add Transaction modal ─────────────────────────────────────────────
    mtx_title_add:    'Add Transaction',
    mtx_title_edit:   'Edit Transaction',
    mtx_close:        'Close',
    mtx_expense:      'Expense',
    mtx_income:       'Income',
    mtx_amount_label: 'Amount',
    mtx_cat_label:    'Category',
    mtx_desc_label:   'Description',
    mtx_desc_ph:      'e.g. Lunch',
    mtx_date_label:   'Date',
    mtx_cancel:       'Cancel',
    mtx_saving:       '...Saving',
    mtx_save:         'Save',
    mtx_err_amount:   'Enter amount',
    mtx_err_invalid:  'Enter a valid amount',
    mtx_err_large:    'Amount is too large',
    mtx_err_date:     'Enter date',
    mtx_err_future:   'Future date not allowed',

    // ── Add Debt modal ────────────────────────────────────────────────────
    mdb_title_add:    'Add Debt',
    mdb_title_edit:   'Edit Debt',
    mdb_close:        'Close',
    mdb_borrowed:     'I Borrowed',
    mdb_lent:         'I Lent',
    mdb_name_label:   "Person's Name",
    mdb_name_ph:      'e.g. John',
    mdb_amount_label: 'Amount',
    mdb_date_label:   'Date',
    mdb_note_label:   'Note (optional)',
    mdb_note_ph:      'e.g. Return at month end',
    mdb_cancel:       'Cancel',
    mdb_saving:       '...Saving',
    mdb_save:         'Save',
    mdb_err_name:     'Enter name',
    mdb_err_name_long:'Name is too long',
    mdb_err_amount:   'Enter amount',
    mdb_err_invalid:  'Enter a valid amount',
    mdb_err_large:    'Amount is too large',
    mdb_err_date:     'Enter date',

    // ── Budget modal ──────────────────────────────────────────────────────
    mb_title:        'Set Monthly Budget',
    mb_close:        'Close',
    mb_desc:         "Set the maximum amount you want to spend this month. We'll notify you when you're near the limit.",
    mb_amount_label: 'Budget Amount',
    mb_cancel:       'Cancel',
    mb_confirm:      'Confirm',
    mb_err_invalid:  'Enter a valid amount',
    mb_err_large:    'Amount is too large',

    // ── Widgets ───────────────────────────────────────────────────────────
    w_edit:   'Edit',
    w_delete: 'Delete',
    w_settle: 'Settle',

    // ── App-level toasts & dialogs ────────────────────────────────────────
    app_tx_updated:      'Transaction updated',
    app_tx_saved:        'Transaction saved',
    app_debt_updated:    'Debt updated',
    app_debt_saved:      'Debt saved',
    app_debt_settled:    'Marked as settled',
    app_tx_deleted:      'Transaction deleted',
    app_budget_saved:    'Budget saved',
    dlg_delete_tx_title: 'Delete Transaction',
    dlg_delete_tx_msg:   'Delete "{desc}" — ৳{amt}?',
    dlg_delete_tx_ok:    'Delete',
    dlg_settle_title:    'Confirm Settlement',
    dlg_settle_msg:      '{name} — ৳{amt} will be marked as settled.',
    dlg_settle_ok:       'Settle',
    dlg_signout_title:   'Sign Out',
    dlg_signout_msg:     'Do you want to sign out? Your data will remain on this device in guest mode.',
    dlg_signout_ok:      'Sign Out',
    toast_signout:       'Signed out',
    toast_signout_err:   'Sign out failed',
  },
};

// Template string helper: t('key', { x: val }) → fills {x} in the string
window.t = function(key, vars) {
  const lang = window.AHLang || 'bn';
  let str = (window.AHStrings[lang] || window.AHStrings.bn)[key];
  if (str === undefined) str = (window.AHStrings.bn)[key] || key;
  if (vars) {
    Object.keys(vars).forEach(function(k) {
      str = str.replace(new RegExp('\\{' + k + '\\}', 'g'), vars[k]);
    });
  }
  return str;
};
